In [15]:
import pandas as pd
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [17]:
path = '/content/drive/MyDrive/praktikum 11/data/UFO_sightings_Spain.csv'

In [18]:
df = pd.read_csv(path)
df

,longitude,latitude,year,Cow incidents,Crop circle found,Alien sighted,Abduction event
0,-5.589385,42.482207,1915,Yes,No,No,No
1,-8.021037,43.018699,1599,Yes,No,No,No
2,-7.536301,42.233816,1923,Yes,No,No,No
3,-4.288818,42.106205,1576,Yes,No,No,No
4,-6.496170,42.212547,1786,Yes,No,No,No
...,...,...,...,...,...,...,...
275,-2.984226,38.129384,1853,No,Yes,Yes,Yes
276,-2.223036,38.337168,1645,No,Yes,Yes,Yes
277,-2.392218,37.995160,1937,No,No,Yes,No
278,-2.454239,38.063602,1956,No,No,Yes,Yes
279,-2.186605,38.516670,1920,No,No,Yes,Yes

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   longitude          280 non-null    float64
 1   latitude           280 non-null    float64
 2   year               280 non-null    int64
 3   Cow incidents      280 non-null    object
 4   Crop circle found  280 non-null    object
 5   Alien sighted      280 non-null    object
 6   Abduction event    280 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 15.4+ KB

In [20]:
df.isnull().sum()

longitude            0
latitude             0
year                 0
Cow incidents        0
Crop circle found    0
Alien sighted        0
Abduction event      0
dtype: int64

In [21]:
X = df[['longitude', 'latitude']]

In [22]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [23]:
from sklearn.cluster import DBSCAN
dbscan = DBSCAN(eps=0.2, min_samples=5)
df['Cluster_Label'] = dbscan.fit_predict(X_scaled)

In [24]:
df['Cluster_Label_Str'] = df['Cluster_Label'].astype(str)

In [25]:
fig = px.scatter_mapbox(
    df,
    lat="latitude",
    lon="longitude",
    color="Cluster_Label_Str",  # Gunakan label klaster sebagai warna
    hover_data={'longitude': True, 'latitude': True, 'Cluster_Label': True},
    zoom=4.5, # Tingkat zoom agar Spanyol terlihat jelas
    height=600,
    mapbox_style="carto-positron", # Menggunakan peta dasar yang ringan
    title="Peta Klaster Penampakan UFO di Spanyol (DBSCAN)"
)

In [26]:
fig.update_traces(marker=dict(size=10, opacity=0.8))
fig.update_layout(
    legend_title_text='Klaster',
    margin={"r":0,"t":50,"l":0,"b":0}
)